- src/sections/_social_header.jade
Can't test this locally, but I'm pretty sure this is cloudflare switching this to text/rocketscript
As @jdaudier pointed out in gitter, the twitter link is broken on http://dev.marionettejs.com/   I'm guessing this will resolve that.
> Tell cloudflare to ignore the twitter script

- src/sections/_about.jade
- src/sections/_download.jade
- tasks/compile-docs.js
Moving this into a directory is more like the current live site URL
And it keeps us from having to deal with the hardcoded paths ie:
`<link rel="stylesheet" href="../../styles/docs.css">`
> /docs/current.html -> /docs/current/index.html

- gruntfile.js
- tasks/compile-docs.js
- tasks/gitty.js
- tasks/utils/gitty-cache.js
- tasks/utils/tags.js
Resolved https://github.com/marionettejs/marionettejs.com/issues/25
Vastly improves https://github.com/marionettejs/marionettejs.com/pull/38
Allow for cli -TAG=v.X.X.X to override the latest tag.  
Otherwise gets and caches the latest tag on the repo.
Not thrilled with setting the exact same options for `gitty:checkoutTag` and `gitty:releaseTag` Is there a better way?
Wasn't certain of a best location for utils.
I don't think there's a way to utilize a promise for the jade data, so `git:releaseTag` must come before `jade` or you'll get `v.X.X.X` in the HTML.
> Gitty caching and tag util

- src/stylesheets/marionette.scss
@samccone this addresses the issue @jdaudier found with the text jumping to the left for two of the videos when you click on the screenshot and the youtube iframes are loaded
> fixed video slide resizing when image and youtube vid are swapped

- tasks/compile-docs.js
Now removes `'` `.` `:`
Now doesn't dasherize `$` `/`
Now removes `/` and leading/trailing `-`
Solves https://github.com/marionettejs/marionettejs.com/issues/72
> Better github href handlin

- gruntfile.js
- package.json
Might be able to tweak the settings one way or another, but by default the images directory went from 2.4MB to 1.1MB and at first glance I don't see any noticeable quality loss.
Might solve https://github.com/marionettejs/marionettejs.com/issues/59
> Compress images during compile-site

- src/stylesheets/_header.scss
This PR fixes minor UX issue in global navigation component:
https://github.com/marionettejs/marionettejs.com/blob/master/src/stylesheets/_header.scss#L89-L215
The  `a, .left` rule is too wide:
https://github.com/marionettejs/marionettejs.com/blob/master/src/stylesheets/_header.scss#L116-L124
The  `.middot` should not appear to be interactive element. It serves as a lists separator.
Thanks!
> Minor UX fix for navigation list

- src/docs/template.html
- src/stylesheets/docs.scss
This PR corrects brand logo area that is interactive:
From this:
to this:
I opted to move `primary-logo` out of image itself - to parent, so it works now as component. This allowed to avoid an ugly patch:
```
.docs__sidebar > a {
....
}
```
The actual logo dimensions are preserved.
Thanks!
> Wrap logo within link area for better UX

- src/sections/_download.jade
The documentation should use commonly used terms expected to be known to users (as much as possible) I believe.
The shortcuts are not commonly known terms (mostly). That is idea behind this PR:
Thanks!
> Use full NPM command name. Closes #124

- src/stylesheets/_header.scss
When you hover over the dots...
OLD
NEW
> [MINOR] Convert dot hover to arrow instead of I-beam

- src/layouts/layout.jade
The landing page is using the single script covered by build process. Let the supporting browser defer loading this script after page has been parsed entirely - as all dependencies are compromised by this script.
All other scripts on the page are 3rd party scripts. The change applies only to landing page as documentation uses different layout.
Thanks!
> Use defer attribute on landing page script. Closes #151

- src/sections/_contribute.jade
- src/stylesheets/_contribute.scss
This PR effectively adds subclass of existing support link elements. It makes following changes completing #153 subject:
- subclass existing support link class
- use different markup to reflect subclassing
- preserve existing features and dimensions
Thanks!
> Refactor contact links list for consistent UX. Closes #152

- src/stylesheets/_contribute.scss
This is a trivial PR which is a follow up to already merged one: #160. It comes separately as it was not ticketed or discussed and has different subject.
The reason behind this PR is to let users whose devices do not show outlines (for whatever reason, custom css, etc) where they are in navigation - if they do not use hovering/pointing devices:
This PR completes PR #160.
Thanks!
> Add focus state to contact links. Follow up to #160

- bower.json
- gruntfile.js
- src/js/github.js
- src/sections/_contribute.jade
This drops 3rd party library from web page source code:
- remove gh3.js from page
- use custom written code to fetch Marionette stargazers
As a fix it removes developer tool console error :+1:
> Drop gh3.js code with custom implementation. Closes #164

- src/stylesheets/_videos.scss
Quick patch to make text eligible in some scenarios discussed in:
https://github.com/marionettejs/marionettejs.com/issues/116
It can be applied before different markup concept if implemented to support text flowing down.
before:
after:
> Fix overflowing video figure captions

- src/index.jade
The video section should get more prominent and visible position as discussed in original issues ticket. The change is trivial in code - more prominent in generated output and results:
Thanks!
> Swap position of video and screencasts sections. Closes #171

- src/stylesheets/marionette.scss
This PR provides correct declaration order for specificity of single selectors within page. The intent of correct order is visible in code as there is explicit declaration that resets this section base styling - that fails due to specificity (later declared wins with the same specificity):
Without this change there are subtle problems in about section:
where specificity of declarations matters:
Thanks!
> Include about partial after base partial to fix specificity problem

- gruntfile.js
This PR introduces two different targets to be used when building stylesheet via Grunt task. 
One is added specifically for use during web site development and it is called `dev` (yes!). The other is `dist` and both are common lingua-franca here.
The Grunt task is changed so all `compile`-like task will use `dist` target - with compressed output and no source maps being built. The `dev` target sets different settings for Sass compiler and PostCSS processor and there are different files created in `dist` directory. For example the Sass is set to use `nested` settings - otherwise I found that source maps points into incorrect locations in Sass partials (the Sass LibSass used supports only `nested` and `compressed` options I think).
The purpose of this PR is discussed in original issue …
> Enable source maps during development. Closes #175

- src/docs/template.html
This helps during development, when using different protocols on deployment, etc. This fixes a little development problem - instead of going back to root after clicking a logo (the only way to go back without using browser back buttons) one goes to project home page.
This PR fixes this:
Thanks!
> Use root-relative link instead of absolute path for logo link in docs

- src/sections/_header.jade
- src/stylesheets/_header.scss
This PR refactors semantics of hamburger menu to use more user friendly/compliant solution (no divs - yeah) - the same as used in:
https://github.com/twbs/bootstrap/blob/master/docs/_includes/nav/main.html#L4
https://github.com/google/web-starter-kit/blob/master/app/index.html#L41
- change markup to use native button
- change style to retain original design and features
The solution was tested - except of IE. The iOS simulator was used to hunt down and fix a bug (line-height needs to be reset for buttons):
One can now trigger menu via any pointing device/software. 
Thanks!
> Refactor hamburger menu semantics

- src/sections/_header.jade
This PR brings back the basic feature on web page - brand root-based link on prominent page position (think readers).
After this change the brand will using common solution - while retaining its `scroll to top` functionality.
Thanks!
> Correct page semantics using real link with brand

- package.json
This is trivial, maintence PR as it just swaps some lines in `package.json`.
This will stops reordering list when adding another dependency via NPM.
For example: I'm working on some feature that requires adding new dev dependency:
```
npm install --save-dev grunt-browser-sync
```
without this change adding dependency will introduce side changes:
```diff
diff --git a/package.json b/package.json
index f211148..c53a841 100644
--- a/package.json
+++ b/package.json
@@ -35,7 +35,9 @@
"dox": "0.6.1",
"gitty": "samccone/gitty",
"grunt": "0.4.5",
+    "grunt-browser-sync": "^1.9.1",
"grunt-contrib-clean": "0.6.0",
+    "grunt-contrib-concat": "0.5.0",
"grunt-contrib-connect": "0.9.0",
"grunt-contrib-copy": "0.5.0",
"grunt-contrib-imagemin": "0.9.2",
@@ -53,7 +55,6 @@
"marked": "0.3.2",
"mkdirp": …
```
> Fix NPM development dependencies order

- gruntfile.js
- src/data/videos.json
- src/sections/_videos.jade
This PR introduces data driven videos section template. The purpose of this PR is to:
- simplify development (smaller template written in Jade - less errors)
- simplify maintenance like adding new content, reordering, typo fixes, etc
- make other changes less tedious (e.g. add additional markup to integrate with search engines via meta tags)
The changes:
- store information about videos in JSON data file
- modify Grunt task to use data source files for Jade templates
- add dedicated watch task to watch for changes in data files
- refactor videos template to use data at compile time
The names of attributes in `videos.json` file are based on YouTube JavaScript/JSONP naming conventions:
https://developers.google.com/youtube/2.0/developers_guide_jsonc
while embedded external `link` uses …
> Introduce data driven videos template. Closes #184

- gruntfile.js
This is trivial, maintenance PR:
We used preHTML and postHTML for CSS related compilation which
was probably due to a simple omission or the copy and paste curse
This PR brings back intended notifications I think:
> Show correct notification when CSS changes

- gruntfile.js
- src/data/books.json
- src/sections/_books.jade
This PR is a follow up to ticket discussing data driven templates:
https://github.com/marionettejs/marionettejs.com/issues/184
and previous - already merged PR:
https://github.com/marionettejs/marionettejs.com/pull/185
This PR introduces similar changes as in #185 and:
- adds JSON file for books information
- modifies Grunt file to use data during compile
- refactors books template file to use data
The changes introduced by PR should have no side effect and does not change rendering context, order or markup.
The reasoning behind this PR is similar to #185: simplify future development and maintenance. 
```diff
commit bc37f111f5aa61cbdf3d9973389075a46b779084
Author: Peter Blazejewicz <peter.blazejewicz@gmail.com>
Date:   Sun Feb 1 21:11:28 2015 +0100
Use data driven books template
- add …
```
> Use data driven books template

- src/stylesheets/docs.scss
Small fix for better UX:
- a link has the same vertical padding now
- change nav margin to offset links vertical padding changes
No visual change :)
before:
after:
> Space clickable area of links evenly. Fixes #197

- src/sections/_footer.jade
- src/sections/_header.jade
- src/stylesheets/_base.scss
- src/stylesheets/_header.scss
This is a set of small commits that:
- adds fallback to use `#top` HTML5 anchor 
- introduces use of `header` tag in header section (HTML5)
- replaces `section` tag within `header` tag with `div` which which is better suited to be used as container. This commit introduces subcomponent to global navigation `__section` to work around dependency in existing code on explicit tag names
- fixes a problem - visible only on Firefox browsers - with global navigation heights:  
- introduces `nav` element as standalone container for navigation elements. This change requires refactoring existing stylesheet code as `ul` list is no longer top container here - it is just a navigation subcomponent (similar solution is used e.g. in Bootstrap: 
https://github.com/twbs/bootstrap/blob/master/less/navs.less#L1 …
> Refactor markup in header and navigation section of page

- src/sections/_footer.jade
- src/sections/_header.jade
- src/sections/_screencasts.jade
- src/sections/_stickers.jade
- src/stylesheets/_footer.scss
When working on previous PR these ones should go into separate PR:
- better descriptive text for alts where required (sticker on a laptop or the Marionette.js text)
- empty alt text where not required and allowed by specification (like in screencast section):
- now we can copy `Made with ♥ by all of us` from the page :)
Thanks!
> Markup small changes and corrections

- src/sections/_companies.jade
The addresses still resolve to `host` but services behind them are dead. The links return 404 for users and crawlers.
Thanks!
> Remove dead links. Closes #204

- src/sections/_about.jade
- src/sections/_code_samples.jade
- src/sections/_downloads.jade
- src/sections/_footer.jade
- src/sections/_header.jade
Add `notranslate` class to other text content within page to skip that content from Transifex Live translation.
See #216
This covers most of filenames, version tags, code instructions and similar content that should be skipped
by Transifex translation service
Thanks!
> Add notranslate class to skip Transifex Live translation. See #216

- src/stylesheets/_header.scss
- src/stylesheets/_ui.scss
This PR fixes some outstanding issues described in #215 that became ostensible when applying multi-language strings to current design.
Simply:
- get standard styles used to style text in link/button elements
- use min-width as advise where appropriate. Otherwise clip text if we use fixed width (and refactor later)
> Fix/buttons text diplay. Closes #215

- src/docs/template.html
This PR adds links to favicon/apple-touch icon to documentation template - missing as pointed in #224
Thanks!
> Add favicon/apple icon to docs template. See #224

- src/docs/template.html
Not sure this is the correct fix but file.title is already available at `compile-docs.js`, see map() returned hash in `Compiler.readFiles()`
> Fixes #224

- src/sections/_inspector.jade
Add WebApplication micro data based on Google Chrome Web store
micro data used by Google to describe Inspector
(minus ratings and other dynamic data)
This PR is intended to improve Inspector indexing cababilities - it already has very good indexing and reachability via Google.
This PR adds following semantics:
```
webapplication
itemType = http://schema.org/WebApplication
name = Marionette Inspector - Chrome Extension
url = http://chrome.google.com/webstore/detail/marionette-inspector/fbgfjlockdhidoaempmjcddibjklhpka
image
href = images/screenshots/inspector-screenshots.gif
text = Marionette Inspector
description = A world-class inspector for exploring your application's views, models, events and more. You won't know how you got by without it.
downloadurl
href = …
```
> Add micro data for Marionette Inspector

- gruntfile.js
- src/robots.txt
This PR introduces `robots.txt` required by Twitter to validate (approve) our TwitterCard as explained #255 - the `robots.txt` are also used by crawlers - so this will be helpful.
- add robots.txt file
- add Grunt task target to include in dist
In the future we could add `humans.txt` btw:
http://humanstxt.org/
https://github.com/h5bp/html5-boilerplate/blob/master/src/humans.txt
Thanks!
> Add robots.txt to web site project. Closes #255

- gruntfile.js
- src/api/class.hbs
- src/docs/template.html
- src/layouts/inspector-layout.jade
- src/layouts/layout.jade
This PR changes how favicon.ico is implemented - we just use now H5PB best practise - just place .ico at the root and avoid relative paths (with dynamic website we would render path at server with helpers):
- rewrite copy assets tag to exclude .ico
- add .ico copy task to non-assets copy target
- remove references to favicon link tag
- update all templates to point how favicon is implemented
One favicon to rule them all: see http://git.io/Ak0N
Thanks!
> Place favicon.ico in the root directory. Fixes #268

- src/sections/_inspector.jade
This PR fixes a bug (missing operating system) and adds category of Inspector:
- 'operating system' is required
- 'application category' better describes its purpose
Values based on Inspector home page within Google Web Store
after:
```
name:	Marionette Inspector - Chrome Extension
operatingSystem:	Chrome
applicationCategory:	Developer Tools
url:	http://chrome.google.com/webstore/detail/marionette-inspector/fbgfjlockdhidoaempmjcddibjklhpka
image:	http://www.example.com/images/screenshots/inspector-screenshots.gif
description:	A world-class inspector for exploring your application's views, models, events and more. You won't know how you got by without it.
downloadUrl:	http://chrome.google.com/webstore/detail/marionette-inspector/fbgfjlockdhidoaempmjcddibjklhpka
```
> Add missing Inspetor properties

- src/js/script.js
- src/sections/_videos.jade
- src/stylesheets/_videos.scss
This PR ditches non-native *mouse-only* div+span combination and introduces existing interactive elements as videos navigation:
- replace non-native elements with native navigation elements
- handle all range of user input to trigger navigation
- update section structure to reflect how content is organized
- slim down section style as native elements have these built-in
- add textual context to next and previous elements
- update client code to reflect what is a button and what is a span
By doing this we expose a range different navigation solution (mosue, keyboard, whatever) and by removing div+span noice improving the sementic of content.
```
section
header
previous video
[videos ......]
next video
```
See where the mouse is, I can navigate via keyboard or voice commands:
Thanks!
TODO: …
> Introduce native navigation for videos. Closes #279

- src/js/script.js
After this commit there will be consistent UX pattern for Marionette
logo/brand on top/left corner always pointing to home page
The subject and 'whys` are discussed in #270 
Thanks!
> Remove scroll effect from logo/brand. Closes #270

- src/sections/_footer.jade
- src/stylesheets/_back_to_top_button.scss
- src/stylesheets/_variables.scss
This PR shave some output code, improves development and:
- apply hidden text via existing helper class (so text is within markup but no longer visible directly)
- remove declarations that are no longer required to hide text (as our text is now hidden we don't need another declarations specifically for this element and its text)
- change location of z-index value to future proof indexing (element z-index is now constant in global variables)
- apply minimum padding from screen edge (useful on mobiles - to not tap on this accidentally)
- apply minimum tap target area (using iOS as reference - to help tap on this when intended by user)
- remove middle breakpoint as not useful with new tap size (the height of element is now nearly the same as in large breakpoint - there is no real difference …
> Refactor back top top style details

- src/sections/_about.jade
- src/stylesheets/_about.scss
This makes the page easier to read, and helps the reader to know why the
elements and blocks are grouped together. This should also benefit our
SEO by increasing the number of times marionette shows up on the page in
a h2 tag.
> Add section headlines to main page.

- src/download/sections/_downloads.jade
- src/download/sections/_header.jade
- src/download/sections/_package_info.jade
- src/sections/_downloads.jade
- src/stylesheets/_base.scss
- src/stylesheets/_downloads.scss
- src/stylesheets/_header.scss
- improve markup - shave and trim elements - use small inside of headers for
example - which is more natural and better controller in reponsive pages
- download section is now linked in 2 distinct ways. It cannot be just hidden as
users are able to use links on any device - so the content should be visible.
Remove .hidden-xs which was OK without direct links - now it's invalid UX
- remove div.section-header - just apply .section-header directly to headers (!)
- add sectioning of content using different levels of headers h2 > h3 (> h4)
- add small copy line to download section
- add "Install ..." to describe what *with* is for
- add semantics to Bower, Npm
- remove microformats properties non-applicable yet to download page
- add util header classes to correct styling while applying …
> Rewrite download section(s) markup and styles

- src/download/index.jade
- src/layouts/layout.jade
This PR adds basic blocks to web site main layout file to allow more flexible content authoring across pages:
- introduce blocks for main components of page: meta, title, TwitterCards,
OpenGraph, content, scripts, styles, GoogleAnalytics
- use different title and descriptions on downloads page to not hurt our web page
accessibility on the net
Using blocks will allows us to also use per-page specific styles/scripts to avoid problems like #302
> Start using blocks in main layout file

- src/download/sections/_package_info.jade
- src/index.jade
- src/layouts/layout.jade
- src/sections/_companies.jade
- src/sections/_footer.jade
This PR fixes one of standing our issues on download page:
* no footer
* bottom of page usage
- add footer block to main template
- change markup of bottom most sections to wrap correctly
- use footer on all pages based on main template
> Refactor footer section

- src/stylesheets/_videos.scss
This PR is a quick fix for #283 issue.
As filling shape is overoptimized and removed let's
add small background to fill the hole.
Remove when #283 is fixed via npm update
> Add hot-fix for #283

- src/inspector/index.jade
- src/stylesheets/inspector/index.scss
This PR renames a grid-row like named class used on Inspector landing page. See #324 for details why these rename is necessary.
This ad-hoc class seems to work as row of content in a grid - hence
current name is rewritten to be more explicit and fix
issue at the same time
> Rename content row class. Closes #324

- gruntfile.js
- src/layouts/inspector-layout.jade
- src/layouts/layout.jade
Move links to the header - the `grunt-critical` task will convert links
on the home page only - on other pages we still should keep links
to stylesheets in the header to avoid flash of unstyled content.
This probably is similar to what was already mentioned in #288 PR.
- all stylesheets in the same logic block
- all stylesheets in the same order in all templates
That's hard to catch this with LICE, as that flash is just a blink of seconds and I failed to capture it via Lice. Just try to reload Inspector page with cache disabled:
http://marionettejs.com/inspector
/cc @jdaudier
> Fix flash of page content

- src/layouts/inspector-layout.jade
The font is blocking resource, saved bytes for this one.
Though it could be already cached - but still counts as bug fix.
Questrial is used on all other pages.
The Firefox has builtin feature to list all fonts used on a web page - I used it to verify with a tool what already visible in used code.
Thanks!
> Remove link to unused font. Fixes #327

- package.json
- src/stylesheets/_videos.scss
I'm no longer able to repeat locally problem with SVGs with updated `critical`/`grunt-critical`:
https://github.com/addyosmani/critical/releases/tag/v0.5.5
https://github.com/bezoerb/grunt-critical/releases/tag/v0.1.2
This PR reverts a patch fix for 283 and bumps `grunt-critical` requirements.
This PR should be verified by local PR test and fresh `npm install` and then `grunt compile-all`
@samccone I know you're busy :)
> YouTube button regression Fix/283 

- gruntfile.js
- package.json
- src/sections/_nav.jade
This PR takes care of minimising inlined polyfill code added with #344 and minimising concatenated website JavaScript code:
- add Grunt UglifyJS task dependency
- minify inlined JavaScript in development and production
- minify main source code in production only
Discussed here:
https://github.com/marionettejs/marionettejs.com/pull/344#issuecomment-77778438
The minimising inlined code is done both during development and built to not overcomplicate build phase:
Thanks!
> Minify JavaScript source code

- src/docco/marionette.css
- src/docco/marionette.jst
Improve basic markup of Docco custom template
- modern tags
- some Schema.org
- all lowercase
Fix semicolon
Such silly code error raises warnings in Safari
Thanks!
> Change/refactor markup in Docco custom template

- gruntfile.js
- package.json
- tasks/compile-annotated-src.js
:rocket: :rocket: :rocket: :rocket: 
------
With this people can now visit 
http://marionettejs.com/annotated-src/backbone.marionette/
http://marionettejs.com/annotated-src/v2.0.1/
http://marionettejs.com/annotated-src/v2.3.0/
http://marionettejs.com/annotated-src/v1.8.8/
This is a huge win for people using marionette, really excited to get this one in :clap:
> Add versioned docco builds.

- src/docco/marionette.css
No easy fix for this one as we use long words for
object names (via dot notation).
The solution is based on similar problem from CSS Tricks:
http://goo.gl/EGJwGY
> Add word-break for headers. Closes #362

- src/docs/template.hbs
- tasks/compile-docs.js
Grabs the first paragraph from the doc and uses that as a seo.description. Then fills out the usual open graph and twitter card details.
Tried to figure out howto get the date of the tag (to use for dc.created), but couldn't figure out a reliable process to put into gitty.
> Improves seo metadata for api docs

- src/docs/template.hbs
This fixes url used in OpenGraph. They do not want redirects:
> Fix url that causes redirects in OpenGraph

- src/docs/template.hbs
As noted in #367 comment: https://github.com/marionettejs/marionettejs.com/pull/367#discussion_r26250677
Twitter recommends to not use the same image that could be reused across
multiple pages - like here with documentation pages.
Image is optional for this type of card
> Remove static image as per Twitter recomendation

- tasks/compile-downloads.sh
This fixes two invalid urls used in compile-download
custom task. I've found that when writing Npm Download based
version of the same task:
```
curl -i https://raw.github.com/marionettejs/backbone.marionette/master/lib/core/backbone.marionette.map
HTTP/1.1 301 Moved Permanently
Date: Sat, 14 Mar 2015 17:09:50 GMT
Server: Apache
Location: https://raw.githubusercontent.com/marionettejs/backbone.marionette/master/lib/core/backbone.marionette.map
Content-Length: 0
Accept-Ranges: bytes
Via: 1.1 varnish
Age: 0
X-Served-By: cache-fra1230-FRA
X-Cache: MISS
X-Cache-Hits: 0
Vary: Accept-Encoding
```
```
curl -i https://raw.github.com/marionettejs/backbone.marionette/master/lib/backbone.marionette.map
HTTP/1.1 301 Moved Permanently
Date: Sat, 14 Mar 2015 17:11:31 GMT
Server: Apache
Location: …
```
> Fix invalid urls in custom task

- src/sections/_examples.jade
Use WebApplication schema to provide feature rich
description to Marionette example applications:
- schema based on https://schema.org/WebApplication
- all required field are provided
- the changes do not change layout at all
- the changes provides better description under readers
The generated microdata:
```
webapplication
itemType = http://schema.org/WebApplication
name = Marionette Wires
applicationcategory = http://schema.org/WebApplication
url = http://www.marionettewires.com
screenshot
href = images/screenshots/wires.png
text = Marionette Wires
description = An opinionated Marionette starter app.
operatingsystem = Requirements: modern web browsers
featurelist = BrowserifyBabel (ES6)HandlebarsGulp
webapplication
itemType = http://schema.org/WebApplication
name = Gistbook …
```
> Add microdata schema to example applications

- src/stylesheets/pages/partials/_inspector.scss
Inspector CTA buttons are not showing up on mobile and this line didn't solve it, so I'm removing it.
I'm using Chrome v41 on Samsung Galaxy S4 (Android 4.4.2)
> Delete style that doesn’t solve inspector button not showing bug

- src/stylesheets/base/_base.scss
- src/stylesheets/base/_shame.scss
This PR moves a Transifex Live code that hides language selector (added by Sam) to Shame file, as this is pure hack - and that is where we should put such things as per best practises.
That is the only declaration from our own code that
uses id selector :(
Thanks!
> Add Transifex Live hack code to shame file

- src/stylesheets/components/_ui.scss
This specific declaration is so general, that it was hard to correctly
state when it is applied, how it was to be overriden and reversed.
For better use add existing helper-class  applied to
instance of component you want to hide
The problem covered by PR:
https://github.com/marionettejs/marionettejs.com/pull/396
cc/ @jdaudier
> Remove too general display block

- src/sections/_examples.jade
@jdaudier 
> I'm seeing this CSS discrepancy between production and local environment. I'm not sure why.
This one:
The .left class artefacts were left from older implementation
during rebasing (Jade :D) on 3 of 4 components
I've wrote meta tags when there were 3 components (3 examples). Then 4 arrived. So after merge I've rebased my PR with meta tags - but that's Jade and I haven't noticed during rebase that `.left` was removed and `.col-4` was extended.
Thanks!
> Remove positioning class. Fixes #405

- src/stylesheets/layout/_header.scss
Padding on the bottom of the masthead causes an unbalanced spacing.
> Remove unnecessary padding in mast head

- src/sections/_companies.jade
This PR allows for the Rapid7 logo to be clickable. A follow up fix to https://github.com/marionettejs/marionettejs.com/pull/363
> Fix markup for rapid7 logo

- package.json
@trezy I had to change this back since it broke my build.
> Update dependency version that broke build

- src/sections/_examples.jade
@peterblazejewicz @samccone @trezy
> Update examples - remove Gistbook link since it's no longer hosted

- src/stylesheets/pages/_updates.scss
This commit changes rendering of markup by
adding small changes to styles on updates page:
- code tag styles
- headers (h4, h5, h6)
- consistent line-height and font-size
etc
before:
after:
If used and found useful, it could be later refactored
to base style for consistent look within the page.
/cc
@jdaudier 
Thanks!
> Improve readability on updates page

- src/js/updates.js
Hi!
This commit adds missing selector to match also content
in markup that is originally hidden from users on updates
page.
Thanks!
/cc
@marionettejs/www
> :bug: Wrap all updates markup with custom class. Fixes #441

- src/js/search.js
- src/layouts/layout.jade
- src/sections/_nav.jade
- src/stylesheets/components/_search.scss
This commit adds some little changes to markup to at
least partially fix #444:
- the critical task does not take into account hidden,
not rendered content - for this reason styling for search
input/bar are not added to critical CSS and unstyled content
impact rendering of top bar during page load. To elevate this
problem an inline style is added to .searchbar selector and
removed via JavaScript related code
- all *search* related assets are now loaded > after main assets
style import is moved and JS inclusion is moved as the content is
not required at all when page is started
- the embedded navbar styles are not applied by critical task. Inline
styling is added to UL element to remove default white space rendered
around top navigation to elevate rendering problem.
Thanks!
> :bug: Enhance rendering of top bar markup. Fixes #444

- tasks/compile-docs.js
- tasks/consts.js
I've added files order for doc.
```
'marionette.application.md',
'marionette.approuter.md',
'marionette.object.md',
'marionette.abstractview.md',
'marionette.view.md',
'marionette.itemview.md',
'marionette.collectionview.md',
'marionette.compositeview.md',
'marionette.layoutview.md',
'marionette.region.md',
'marionette.regionmanager.md'
```
This files will be shown first, then other doc files. 
Also I added some improvements for order functionality.
@scott-w can you verify this order? Is it fine?
> add doc ordered files

- .gitignore
- src/docs/template.hbs
- src/stylesheets/docs.scss
Added 'improve doc button' for docs page. Button will be not visible on small screens. I see there some reason because if you on phone or tablet you will not make pr on gh through this device. Also this btn will not bother you when you reading doc on small screens.
Resolves #465 
P.S. Sorry that I created branch in scope of this repo instead of forking. I was sure that I'm working in forked repo 😞
> add improve doc btn

- src/docs/template.hbs
- tasks/compile-docs.js
- tasks/compilers/additional-resources.js
Added "Current Version" to top of dropdown on docs page. This navigates to `/docs/current`. The current version of the docs will match the content of the docs on the `master` branch rather than linking to a specific version.
The advantage here is that we can release doc improvements without a GitHub release tag.
> Build current docs version from master branch

- tasks/compile-downloads.sh
Static build archives (.zip and .tar.gz) are being generated with a stray "tmp/" prefix.
Here's a fix.
> Remove stray "tmp/" path from static build archives

- grunt/aliases.js
- gruntfile.js
- package.json
- tasks/psi-ngrok.js
- travis-runner.sh
> Make PageSpeed Insights part of CI

- grunt/aliases.js
- src/layouts/layout.jade
- src/partials/_search.jade
- src/sections/_footer.jade
**TL;DR;**
I noticed that our main page is loading in something strange way. Firstly loaded content with css but it all look broken, then loaded normal layout with fancy styles. I made some video to show it (it's with `regular 2g network`, to show it in 'slow motion')
https://monosnap.com/file/P5uuJQIVHXAsBzKnD3CTb7K5q9EbEY
I dig deeper and made some perf tests. So lets go.
First was analyzed `http://marionettejs.com/`
I cloned our site repo and run dev to debug why it is happening. I was really surprised that after running on dev it looks fine but different in scope of css loading.
As you can see there are blocking css, rendering hasn't started because of it, hence no broken html.
I went deeper and run `compile-all` (this is grunt command which is running during deploying). And
(it was …
> Performance improvements for start page

- src/inspector/index.jade
`MarionetteWires.com` domain is expiring in on March 9th, so moving this to the native Heroku URL.
> Update Marionette Wires URL
