src/layouts/layout.jade

Add easter egg to promote inspector

---

src/docs/index.html
src/docs/template.html
src/stylesheets/docs.scss
tasks/compile-docs.js

CSSing elements
Using the page's 1st `<h1>` as menu text
Replaces .md with .html for internal links
Additional fix for page anchors
Added a logo to the bottom of the menu just cuz
Resolves: https://github.com/marionettejs/marionettejs.com/issues/32

Doc impovements

---

src/index.jade
src/sections/_about.jade
src/sections/_header.jade
src/stylesheets/_base.scss
src/stylesheets/_header.scss

It's not everything, but it should help you get started twards bigger and better things
https://github.com/marionettejs/marionettejs.com/issues/52#issuecomment-68579655

Add header starting off point

---

package.json

added rimraf module for tasks/compile-docs.js

---

gruntfile.js
src/docs/template.html
src/layouts/layout.jade

Also add deferred scripts for console play for the docs as well.
css portion of https://github.com/marionettejs/marionettejs.com/issues/57

Compress sass, defer sandbox script

---

src/sections/_who_is_using.jade

https://github.com/marionettejs/marionettejs.com/issues/93 saved the previous PR from breaking these logos.

Logos: use the pngs not the gifs that were deleted

---

bower.json
src/js/script.js
src/layouts/layout.jade
src/sections/_videos.jade
src/stylesheets/_variables.scss
src/stylesheets/marionette.scss

addresses issue #96 
I updated the slider section to be a responsive css3 slider, also made it much more apparent that there are multiple videos, see screenshots below
> NOTE: the arrows for the slider nav are .png files, I know @paulfalgout has done a lot of work with the svg changes so this will need that treatment as well, but its a good start

updated UX for videos section, now have responsive css slider

---

src/sections/_header.jade
src/stylesheets/_header.scss
src/stylesheets/marionette.scss

Just some little things I noticed on the mobile site

Minor styling updates for mobile view

---

src/layouts/layout.jade

The main text content of Marionettejs.com is in English. This is a minor html markup fix. 
Due to use of Jade as preprocessor - the size of commit is quite significant though - I had to add starting tag that was previously rendered by doctype tag shortcut.
The template compiles fine after this change on local machine:
https://gist.github.com/peterblazejewicz/9757192256b744e5fc15
Thanks!

Add language attribute to global template

---

gruntfile.js
src/js/inspector-comment.js

Log inspector notification to console

---

src/js/inspector-comment.js
src/stylesheets/_header.scss

Update top nav

---

README.md
svg-steps.md

@paulfalgout Can you confirm that my steps are correct? Tks!
**UPDATED README**
****
**STEPS**

Add SVG steps - closes #137

---

src/sections/_companies.jade

Update link to Fortune

---

src/sections/_inspector.jade
src/stylesheets/_inspector.scss
src/stylesheets/marionette.scss

This is a follow up to comments in #200:
https://github.com/marionettejs/marionettejs.com/pull/200
- one type of quotes in code section
- no inline styles if possible
- custom section style
- TODO: refactor description to separate component to avoid specificity
- no drop shadow under inspector image
- better alt text for image
Thanks!

Refactor code from PR #200

---

README.md
src/docs/template.html
src/layouts/layout.jade
src/sections/_footer.jade

ping @peterblazejewicz - might wanna check my work since it's really late - tks! And need your email to add you to Hotjar to see the stats.

Add Hotjar heatmap - closes #196

---

README.md

Fixing latest PR typo:
https://github.com/marionettejs/marionettejs.com/pull/208#issuecomment-73773468

Fix missing word in site doc

---

src/sections/_footer.jade

As discussed when adding Hotjar:
https://github.com/marionettejs/marionettejs.com/pull/208#issuecomment-73769045
- separate lines
- distinctive main claim line just by semantics applied to second paragraph
Thanks!

Restructure footer copy line paragraphs

---

src/sections/_inspector.jade

oops... forgot to pull down this change from my home comp from last night

Update inspector description

---

src/layouts/layout.jade

Remove unused flattr script

---

src/sections/_code_samples.jade
src/sections/_header.jade
src/stylesheets/_header.scss

This PR fixes some problems with use or lack of correct header in text content - there is no visual change on how we present content - but PR corrects things how content is structured, indexed and prioritised.
Thanks!

Fixes to headers in markup

---

src/sections/_header.jade

Remove twitter from header area.

---

src/stylesheets/_code_samples.scss

- apply unified broder radius to section components
- use different border radius on different screens depending on layout

Refactor code samples styles. Fixes #245

---

gruntfile.js
package.json
src/layouts/layout.jade

Tested locally and works like a charm

Add critical css.

---

src/sections/_about.jade
src/sections/_screencasts.jade
src/stylesheets/_header.scss
src/stylesheets/_mobile.scss
src/stylesheets/marionette.scss

**Before**
**After**
I also hid the requirements, screencasts, and inspector install button on mobile, since they are all pretty useless actions on mobile

improve mobile site

---

src/stylesheets/inspector/index.scss

Fix image rendering of chome icon

---

src/js/script.js
src/sections/_code_samples.jade

Quick fix related to correct selector used to initialize jQuery plugin
- correct selector to init plugin
- cache reference to elements
- selector clearly marked for use in JS
Thanks!

Fix equal heights script

---

gruntfile.js
src/download/index.jade
src/download/sections/_downloads.jade
src/download/sections/_header.jade
src/download/sections/_package_info.jade
src/layouts/layout.jade
src/sections/_header.jade
src/sections/_nav.jade
src/stylesheets/_downloads.scss

Add Download page

---

src/download/sections/_downloads.jade
src/download/sections/_header.jade
src/download/sections/_package_info.jade
src/sections/_downloads.jade
src/sections/_nav.jade
src/stylesheets/_downloads.scss

Plus a few other misc minor verbiage updates
****

Fix broken docs link on Downloads page

---

src/data/videos.json
src/sections/_videos.jade

This PR enhances textual content of web page in videos section that it can be finally read:
https://soundcloud.com/peter-blazejewicz/video-tags-text-to-speech-sample
```
Marionette Behaviors
Jason Laster explains how to use Marionette Behaviors. Slides: http://mbx.cm/t/9GBSw Sponsored by: http://www.infor.com
Marionette.js: http://marionettejs.com Dancing with Marionette Meetup: http://...
Marionette Behaviors
Backbone.Wreqr
James Smith explains how you can use Backbone.Wreqr. Slides: http://mbx.cm/t/TtNgU Sponsored by: http://www.infor.com Marionette.js:
http://marionettejs.com Dancing with Marionette Meetup: http://ww...
Backbone.Wreqr
```
or analyzed:
```
Item 
type:	http://schema.org/videoobject
property:	
name:	James Smith - Marionette The Backbone Framework
description:	
embedurl: …
```

Add semantic meaning to videos section content.

---

src/js/script.js
src/sections/_videos.jade
src/stylesheets/_videos.scss

Add ripple effect to video slider buttons

---

src/stylesheets/_footer.scss

This PR shaves some declaration out of compiled output, while improving UX and development:
- remove unused properties as we are using different content layout now
- introduce variables for frequently repeated colors
- compress declaration where applicable
- improve UX

Refactor footer style

---

gruntfile.js

Source maps are nice, and we are nice. Let's use them :)
nice nice

Sourcemaps .. because 2015

---

gruntfile.js

Another `extra` comma to be removed

Remove extra commas, other changes to build file [redacted]

---

src/download/sections/_header.jade

Fix typo on download page

---

src/stylesheets/components/_buttons.scss
src/stylesheets/marionette.scss

Based on recent discussion in this issue #267 and requirement to move forward with optimizing source and output code, here is a first of such (hope) improvements that brings extracted from current version abstracted *button* like UI component that can be applied to any tag (expected use on a, button, input tags) together with two concrete versions (`primary`/`secondary`) of two existing patterns used on our web site.
- add components directory
- add reusable base `button` class
- add two base subclasses based on current design
- make sure we are using common UX pattern in component implementation
- add reusable mixin to quickly generate other subclasses
So there is one *abstract* class that has no background, border or color exact definition and can be extended in subclasses here.
The …

Add Button UI component into source code

---

src/js/script.js

This PR quickly patches a client code that needs to be refactored (restructured) further. We just prevents from runtime errors.
Only this one safety check is required in entire block code
The rest of code gracefully fails though eats some CPU cycles
It will be refactored shortly

Add safety check to code block. Fixes #302

---

src/stylesheets/_videos.scss

@jdaudier 
It just slightly darken color of background  to give visual clues.

Add hover/focus visual clues. Closes #282

---

src/api/class.hbs
src/docs/index.hbs
src/docs/template.hbs

Fixing markup:
- add doctype declaration
- add IE compatibility mode
- add lang and charset
- add micro tags semantics

Update docs templates markup

---

src/inspector/index.jade

I've been following this rule where all external sites open in a new window and internal pages don't

[MINOR] Update Etsy link to open in a new window

---

src/data/videos.json

Updated order of videos - moved BB plugin video to show up later

---

src/inspector/index.jade

This PR changes texts of paragraphs using text written by @jdaudier:
https://github.com/marionettejs/marionettejs.com/pull/332#issuecomment-77004001
cc @jdaudier @jasonLaster

Rewrite Inspector paragraphs text. Closes #333

---

src/inspector/index.jade

Links to: https://marionette-wires.herokuapp.com/

Link to Wires in the Inspector page

---

bower.json
src/js/script.js
src/sections/_nav.jade

This allows even on a slow network for the menu interaction to work
right away, as compared to when ALL of the JS has loaded.
Fixes #343

Inline critical menu JS

---

gruntfile.js
src/docco/marionette.css
src/docco/marionette.jst

To start writing our custom theme as in #90
this commit:
- creates our own copy of default Docco template files
- changes Grunt task options to use our own template
From this point Mj source code will be outputted by Docco
with this updated theme.
Example output:
http://jsbin.com/ponilu/
Thanks!

Scaffold first version of custom Docco template

---

src/api/class.hbs
src/docs/template.hbs
src/layouts/inspector-layout.jade
src/layouts/layout.jade

Just cleanup and stay up-to-date:
Lowercase is new black. See:
http://git.io/puYK

Change X-UA-Compatible to lowercase

---

src/sections/_header.jade

@peterblazejewicz is this ok? I noticed we went up a folder and then went back in.

Update path to nav

---

gruntfile.js

This fixes code linting and subsequent build errors after dependency updates.
See #385 for details.

Fix code linting after deps update. Closes #385

---

src/stylesheets/base/_base.scss

Little, small change to reduce code

Merge two declarations of the same helper into one

---

src/stylesheets/base/_shame.scss
src/stylesheets/marionette.scss

We will need this to host some already declarations from other partials.
The concept of `shame` file is described here:
http://sass-guidelin.es/#shame-file
http://csswizardry.com/2013/04/shame-css-full-net-interview/
And we need it for code like:
https://github.com/marionettejs/marionettejs.com/blob/master/src/stylesheets/base/_base.scss#L143-L148
(which will be moved after this PR in other change).

Introduce Shame file as per common practise

---

src/stylesheets/components/_ui.scss
src/stylesheets/pages/partials/_inspector.scss

Fix btn alignment for mobile views - closes #402

---

src/sections/_examples.jade

Replace RequireJS with Babel + Handlebars + JSPM

Update Streamus description

---

.travis.yml
package.json

Just to make sure Travis always builds right. I also added an `engines` config to the `package.json` for people that know to look for that.

Update Node version to 0.12

---

.jshintrc
src/index.jade
src/js/github.js
src/sections/_team.jade
src/stylesheets/components/_team_member.scss
src/stylesheets/marionette.scss

[#406] Add Marionette Team section

---

.jshintrc
bower.json
grunt/concat.js
grunt/jade.js
grunt/sass.js
src/js/updates.js
src/sections/_nav.jade
src/stylesheets/pages/_updates.scss
src/stylesheets/pages/partials/_companies.scss
src/stylesheets/updates.scss
src/stylesheets/utils/_helpers.scss
src/updates/index.jade
src/updates/sections/_changelog.jade
src/updates/sections/_header.jade

Added "updates" button to check new releases

---

tasks/compile-docs.js

PR due to task #447 
I've commited also changes to submodule, is it ok?

Add doc files order

---

tasks/utils/gitty-cache.js
tasks/utils/tags.js

remove invalid tags for docs

---

src/docs/template.hbs
src/stylesheets/docs.scss

Now we have some not good look in left menu and console error `TypeError: Cannot use 'in' operator to search for 'default' in undefined`

Fix style and console issues for doc

---

tasks/compile-downloads.sh

Bash script didn't want to copy files into dir with is not present.
Resolves #478

Fix download page

---

grunt/concat.js
grunt/copy.js
grunt/watch.js
src/docs/template.hbs
src/js/gitter-chat.js
src/layouts/layout.jade
src/sections/_nav.jade
src/stylesheets/components/_ui.scss
src/stylesheets/layout/_header.scss

Add possibility to open gitter chat on site

---

grunt/uglify.js

Add right files sources for uglifying

---

src/sections/_footer.jade

Fix mixed content error for Google fonts. Closes #497

---

README.md
src/docs/template.hbs
travis-runner.sh
yarn.lock

Fixed for docs pages, related to #497

Resources not loaded via https

---

travis-runner.sh

Reverts marionettejs/marionettejs.com#502

Revert "debug-ci-deploy"

---

travis-runner.sh

Reverts marionettejs/marionettejs.com#504

Revert "push in other manner"
